FROM php:7.4.9-fpm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libzip-dev \
        default-mysql-client \
        less \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN docker-php-ext-configure zip && \
    docker-php-ext-install zip && \
    docker-php-ext-install pdo_mysql