version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ../mysql/db:/docker-entrypoint-initdb.d
      - ../logs/mysql:/var/log/mysql
      - ../mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"
    restart: always

  api-server:
    mem_limit: '4096m' # VM等でリソースをきっちり制限して動かすつもりがないので適当に
    build: ../php # ここでphpディレクトリのDockerfileを利用してrun
    command: php-fpm
    entrypoint:
      - dockerize # 普段はスクリプトで起動を待っている処理。世間ではdockerizeコマンドを実行するらしい。
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    volumes:
      - ../mysql/db:/var/www/mysql/db
      - ../fixture:/var/www/fixture
      - ../php/isuumo.php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../php:/var/www/isuumo
    environment:
      MYSQL_DBNAME: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_HOST: mysql
      SERVER_PORT: 9000
    ports:
      - 9000:9000
    depends_on:
      - mysql

  frontend:
    build: ../frontend
    volumes:
      - ../nginx/out:/frontend/out

  nginx:
    build: ../nginx
    volumes:
        - ../nginx/isuumo.php.conf:/etc/nginx/conf.d/default.conf
        - ../nginx/out:/var/www/data
    ports:
      - "1323:1323"
    entrypoint: []
    environment:
      API_SERVER: api-server
    depends_on:
      - frontend
    command: nginx -g 'daemon off;'
